### PR TITLE
Make some improvements to scss

### PR DESCRIPTION
**Pull request by oraNod**
Fixes https://github.com/ansible/docsite/issues/169 

- Removes clipboard and unused styles
- Removes unused card styles
- Simplifies the page title classes
- Uses a single class for the page logo images

### CODE REVIEW

**Comment by Andersson007** [comment]
@oraNod is there an easy way to see the result of this PR (or any other PRs raised here) in a browser?

**Comment by Andersson007** [comment]
@oraNod or maybe at least a couple of screenshoots before-after with highlighting of changed things would be great to have.

**Comment by oraNod** [comment]
@Andersson007 This PR doesn't make any changes that are visible to the user. I did think about before/after screenshots but they would show the same thing really. I've condensed some of the scss and removed things the docsite doesn't use, like the clipboard and card styling.

If you still want screengrabs, I can do that. I just build the site locally with a venv using "python build.py". Soon I'll port all the build and deploy stuff to nikola.

**Review by cybette — APPROVED** [review]

**Review by Andersson007 — APPROVED** [review]
@oraNod if it doesn't change the UI, no need for the screenshots:)
removing unused stuff SGTM

**Comment by oraNod** [comment]
Thanks @Andersson007 and @cybette

**Pull request merged**
