### PR TITLE
Add 4.2.2 to the controller oldsite prior versions

### PR DESCRIPTION
**Pull request by oraNod**
Fixes https://github.com/ansible/docsite/issues/168

### CODE REVIEW

**Comment by Andersson007** [comment]
@oraNod if it's possible for you to attach a couple of screenshots before-after with the changed things highlighted it'd be great.

**Comment by oraNod** [comment]
### Tower prior versions page

Current page is here: https://docs.ansible.com/oldsite/automation-tower-prior-versions.html

This PR adds a card for 4.2.2 to prior tower versions. Here's a screenshot:

image

### Translation pages

Current pages are here:

- https://docs.ansible.com/oldsite/automation-tower-japanese-translations.html
- https://docs.ansible.com/oldsite/automation-tower-chinese-translations.html
- https://docs.ansible.com/oldsite/automation-tower-korean-translations.html

This PR adds 4.2.2 to those pages. Here is a screenshot for the _ja translations. It is the same for _zh and _ko.

image

image

**Review by Andersson007 — APPROVED** [review]
LGTM
a thing to consider: would just a list be more readable?

**Comment by oraNod** [comment]
@Andersson007 Thanks. Yes, a list would be more readable for sure. I changed it to a list for the new docsite: https://docs.ansible.com/automation-tower-japanese-translations.html

This PR is for the "legacy" oldsite that we still need to maintain until we get to the point where it's OK to drop the oldsite and the toggle.

**Pull request merged**
